Reduce memory usage, allow selection of multiple metrics in MetricsPane [HZG-208]
hazelcast/hazelcast-diagnostics pull request #7
Opened 2024-11-13 08:54 UTC by hazelcast-alexb

This PR reduces the memory footprint while loading large diagnostics files.

Previously each individual `DiagnosticFile` contained an index for the metric entries contained within it. Now there is a single index per instance of `InstanceDiagnostics`, this hugely reduces the number of index entries needed and allows the tool to load several gigabytes of diagnostic logs.

In addition a number of IDE compiler warnings have been fixed and the `MetricsPane` has been updated to allow selection and comparison of multiple metrics.

2024-11-13 08:54 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org:443/pull/badge/not_signed)](https://cla.hazelcast.org:443/hazelcast/hazelcast-diagnostics?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org:443/hazelcast/hazelcast-diagnostics?pullRequest=7) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org:443/check/hazelcast/hazelcast-diagnostics?pullRequest=7) it.</sub>

2024-11-13 10:26 UTC, JackPGreen requested changes

2024-11-13 10:26 UTC, JackPGreen commented on src/main/java/com/hazelcast/diagnostics/InvocationProfilerPane.java
> +import java.util.stream.Collectors;
```suggestion
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.SortedMap;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
```

I don't think any of these are needed.

2024-11-13 10:26 UTC, JackPGreen commented on src/main/java/com/hazelcast/diagnostics/InstanceDiagnostics.java
> +    public static final String METRIC_RUNTIME_TOTAL_MEMORY = "[metric=runtime.totalMemory]";
Could these be an `enum`?

2024-11-13 15:46 UTC, JamesHazelcast approved these changes
LGTM, we should probably clean up the unused imports before merging, but approving in advance. Thanks for this @hazelcast-alexb!

2024-11-13 15:46 UTC, JamesHazelcast commented on src/main/java/com/hazelcast/diagnostics/InstanceDiagnostics.java
> +    public static final String METRIC_RUNTIME_TOTAL_MEMORY = "[metric=runtime.totalMemory]";
I think this is fine as-is, @hazelcast-alexb has mainly compiled strings used all over the place in this project into constants, and then added to it - I don't think there's much value to be gained from making these enums

2024-11-15 10:42 UTC, JackPGreen approved these changes
Some silly comments from me, but it's totally fine as it is :)

2024-11-15 11:33 UTC, hazelcast-alexb commented on src/main/java/com/hazelcast/diagnostics/InstanceDiagnostics.java
> +            {
Lol. That's a hangover from the last place's code style! Old habits die hard.

2024-11-15 11:50 UTC, merged